---
detect_relations: true
options:
  charset: latin1
  type: InnoDB

administrador:
  columns:
    DNI:
      type: string(45)
      primary: true
      notnull: true
  relations:
    DNI:
      class: usuario
      local: DNI
      foreign: DNI
      foreignAlias: administradors
      onDelete: cascade
      onUpdate: cascade
  indexes:
    DNI_Admin:
      fields: [DNI]
  options:
    charset: latin1

cliente:
  columns:
    DNI:
      type: string(45)
      primary: true
      notnull: true
    N_Pedidos:
      type: integer(4)
      notnull: true
    Desembolso:
      type: decimal(10)
      scale: 2
      notnull: true
  relations:
    DNI:
      class: usuario
      local: DNI
      foreign: DNI
      foreignAlias: clientes
      onDelete: cascade
      onUpdate: cascade
  indexes:
    DNI:
      fields: [DNI]
  options:
    charset: latin1

gestor:
  columns:
    DNI:
      type: string(45)
      primary: true
      notnull: true
  relations:
    DNI:
      class: usuario
      local: DNI
      foreign: DNI
      foreignAlias: gestors
      onDelete: cascade
      onUpdate: cascade
  indexes:
    DNI_Gestor:
      fields: [DNI]
  options:
    charset: latin1

pedido:
  columns:
    Ref:
      type: string(10)
      primary: true
      notnull: true
    DNI_Cliente:
      type: string(45)
      notnull: true
    DNI_Gestor:
      type: string(45)
      notnull: true
    Coste:
      type: decimal(10)
      scale: 2
      notnull: true
    Precio:
      type: decimal(10)
      scale: 2
      notnull: true
    Estado:
      type: string(45)
      notnull: true
    Fecha Pedido:
      type: date
      notnull: true
    Fecha Modificacion:
      type: date
      notnull: true
  relations:
    DNICliente:
      class: cliente
      local: DNI_Cliente
      foreign: DNI
      foreignAlias: pedidoes
      onUpdate: cascade
    DNIGestor:
      class: gestor
      local: DNI_Gestor
      foreign: DNI
      foreignAlias: pedidoes
      onUpdate: cascade
  indexes:
    Cliente:
      fields: [DNI_Cliente]
    DNI_PGestor:
      fields: [DNI_Gestor]
  options:
    charset: latin1

pedido - producto:
  columns:
    Pedido:
      type: string(10)
      notnull: true
    Producto:
      type: string(10)
      notnull: true
  relations:
    Producto:
      class: producto
      local: Producto
      foreign: Ref
      foreignAlias: pedido - productoes
      onUpdate: cascade
    Pedido:
      class: pedido
      local: Pedido
      foreign: Ref
      foreignAlias: pedido - productoes
      onDelete: cascade
      onUpdate: cascade
  indexes:
    Producto:
      fields: [Producto]
    Pedido:
      fields: [Pedido]
  options:
    charset: latin1

producto:
  columns:
    Ref:
      type: string(10)
      primary: true
      notnull: true
    DNI_Gestor:
      type: string(45)
      notnull: true
    Nombre:
      type: string(45)
      notnull: true
    Descripcion:
      type: clob(65535)
      default: null
    Coste:
      type: decimal(10)
      scale: 2
      notnull: true
    Margen:
      type: decimal(10)
      scale: 2
      notnull: true
    Precio:
      type: decimal(10)
      scale: 2
      notnull: true
    Categoria:
      type: string(45)
      notnull: true
    Estado:
      type: string(45)
      notnull: true
  relations:
    DNIGestor:
      class: gestor
      local: DNI_Gestor
      foreign: DNI
      foreignAlias: productoes
      onUpdate: cascade
  indexes:
    DNI_PPGestor:
      fields: [DNI_Gestor]
  options:
    charset: latin1

usuario:
  columns:
    DNI:
      type: string(45)
      primary: true
      notnull: true
    Nombre:
      type: string(45)
      notnull: true
    Apellido1:
      type: string(45)
      notnull: true
    Apellido2:
      type: string(45)
      default: null
    Direccion:
      type: string(45)
      notnull: true
    Telefono:
      type: string(45)
      notnull: true
    Fecha Alta:
      type: date
      notnull: true
    Fecha Ultimo Acceso:
      type: date
      notnull: true
    Estado:
      type: string(45)
      notnull: true
    Email:
      type: string(45)
      notnull: true
    Usuario:
      type: string(45)
      notnull: true
    Clave:
      type: string(45)
      notnull: true
    DNI_Administrador:
      type: string(45)
      notnull: true
  options:
    charset: latin1

