_index:
    pattern:  /
    defaults: { _controller: CasavanaCOBDBundle:Casavana:index }

client:
    pattern:  /client
    defaults: { _controller: CasavanaCOBDBundle:Client:index }

manager:
    pattern:  /manager
    defaults: { _controller: CasavanaCOBDBundle:Manager:index }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
