#
# more information can be found here http://sonata-project.org/bundles/user
#
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

# Enable Doctrine to map the provided entities
#doctrine:
#    orm:
#        entity_managers:
#            default:
#                mappings:
#                    FOSUserBundle: ~
#                    ApplicationSonataUserBundle: ~
#                    SonataUserBundle: ~
